server:
  port: 8081

logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.authjs.dev/realms/master
          jwk-set-uri: https://keycloak.authjs.dev/realms/master/.well-known/openid-configuration